<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\View;
use App\Channel;
use Illuminate\Support\Facades\Cache;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // configure the default string length generated by migrations in order for MySQL to create indexes
        Schema::defaultStringLength(191);

        // Caching channels forever.
        // It is very unlikely that channel will change
        View::composer('*', function ($view) {
            $view->with('channels', Cache::rememberForever('channels', function () {
                return Channel::all();
            }));
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        if ($this->app->isLocal()) {
            $this->app->register(\Barryvdh\Debugbar\ServiceProvider::class);
        }
    }
}
